name: Publish NetGSM Java SDK

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Step 3: Configure Git for version bumping
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      # Step 4: Bump Version for Release
      - name: Bump Version
        id: bump
        run: |
          # Retrieve the current version from the root POM
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current version: $VERSION"

          # Increment the minor version (e.g., 1.0.0 -> 1.1.0)
          NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$2++; $3=0; print}')
          echo "New release version: $NEW_VERSION"

          # Update the version in all modules
          mvn versions:set -DnewVersion=$NEW_VERSION -DprocessAllModules=true

          # Commit the version change
          git add pom.xml 
          git commit -m "Release version $NEW_VERSION"
          git push origin master

      # Step 5: Build with Maven
      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip=true

      # Step 6: Publish to GitHub Packages
      - name: Publish to GitHub Packages
        run: mvn deploy -Dmaven.test.skip=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
